services:
  broker:
    image: rabbitmq:3.11-management
    container_name: spendly-broker-prod
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - broker-data:/var/lib/rabbitmq
    networks:
      - broker-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: spendly-redis-prod
    ports:
      - "6379:6379"
    env_file:
      - .env.broker
    command: >
      sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --user "$$REDIS_USER" on ">$$REDIS_PASSWORD" "~*" "+@all"'
    volumes:
      - redis-data:/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: spendly-backend
    container_name: spendly-backend-prod
    env_file:
      - .env.backend
    environment:
      - PORT=8000
    depends_on:
      broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - broker-network
      - api-network
      - shared

  api:
    image: spendly-api
    container_name: spendly-api-prod
    env_file:
      - .env.api
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/firebase.json
    volumes:
      - ./firebase.json:/app/firebase.json:ro
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - api-network
      - shared
  frontend:
    image: spendly-frontend
    container_name: spendly-frontend-prod
    env_file:
      - .env.frontend
    environment:
      - PORT=3005
    depends_on:
      - api
    networks:
      - api-network
      - shared

volumes:
  broker-data:
  redis-data:

networks:
  broker-network:
    driver: bridge
  api-network:
    driver: bridge
  shared:
    external: true
